
pipeline {
  agent any

  environment {
    AWS_REGION = "ap-south-1"
    ECR_REPO   = "devops-java-app"
    ACCOUNT_ID = "017789174175"
    IMAGE_TAG  = "1.0"
  }

  stages {
    stage('Checkout') {
      steps {
        // Use the same repo Jenkins used to fetch this Jenkinsfile
        checkout scm
        // Diagnostics to prove which repo/commit was checked out
        sh '''
          echo "Repo: $(git remote get-url origin)"
          echo "Commit: $(git rev-parse --short HEAD)"
          ls -la
        '''
      }
    }

    stage('Build & Test (Maven)') {
      steps {
        dir('complete') {
          sh 'chmod +x mvnw'
          sh './mvnw -B clean test'
        }
      }
      post {
        always {
          junit testResults: 'complete/target/surefire-reports/*.xml', allowEmptyResults: true
        }
      }
    }

    stage('Package') {
      steps {
        dir('complete') {
          sh './mvnw -B package'
        }
      }
      post {
        success {
          archiveArtifacts artifacts: 'complete/target/*.jar', fingerprint: true
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('complete') {
          sh 'docker build -t ${ECR_REPO}:${IMAGE_TAG} .'
        }
      }
    }

    stage('Login to ECR') {
      steps {
        sh '''
          aws ecr get-login-password --region ${AWS_REGION} \
          | docker login --username AWS --password-stdin \
            ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
        '''
      }
    }

    stage('Tag & Push Image') {
      steps {
        sh '''
          docker tag ${ECR_REPO}:${IMAGE_TAG} \
            ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}

          docker push \
            ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
        '''
      }
    }
  }

  post {
    always { cleanWs() }
  }
}

